### ISSUE TITLE
Cannot pull image from `ghcr.io/casbin-mesh/casbin-mesh:latest` correctly.

### ISSUE THREAD

**Issue by noneback** [casbin/casbin-mesh#50]
Cannot pull image from `ghcr.io/casbin-mesh/casbin-mesh:latest` correctly.

**Comment by noneback** [comment]
change `ghcr.io/casbin-mesh/casbin-mesh:latest` to `ghcr.io/casbin/casbin-mesh:main` will help.

**Comment by WenyXu** [comment]
I checked the `ghcr.io/casbin-mesh/casbin-mesh:latest`, and it works for me.

**Comment by noneback** [comment]
> I checked the `ghcr.io/casbin-mesh/casbin-mesh:latest`, and it works for me.

A little bit weird. When I try to pull the image, it returns `Error response from daemon: unauthorized`. Maybe it's due to I don't have the right access permission to `casbin-mesh/casbin-mesh`. If so, other users may also not pull its image.

**Comment by noneback** [comment]
By the way, `ghcr.io/casbin/casbin-mesh:main` works while `ghcr.io/casbin/casbin-mesh:latest` don't.
