### ISSUE TITLE
Links in Readme file not opening

### ISSUE THREAD

**Issue by harshalmittal4** [casbin/casbin-mesh#66]
Hello, I'm trying to get familiar with cabin-mesh and noticed that 3 links in Readme are incorrect,
1. models - To setup an Casbin model for a specific namespace, executes following request on /set/model endpoint. See all supported [models](https://casbin.org/docs/en/supported-models).
2. Policies - Let's add policies for the test namespace. See more of [Policies](https://github.com/casbin/casbin-mesh/blob/main)
3. docs - All documents were located in [docs](https://github.com/casbin/casbin-mesh/blob/main/docs) directory.

I suppose `models` link must point to https://casbin.org/docs/supported-models, is this correct? 
Could you also please tell where do `Policies` and `docs` are supposed to redirect, I would like to send a PR

**Comment by hsluoyz** [comment]
@harshalmittal4 

> I suppose models link must point to https://casbin.org/docs/supported-models, is this correct?

yes

> Could you also please tell where do Policies and docs are supposed to redirect

@WenyXu @nodece any clues?

**Comment by WenyXu** [comment]
> Hello, I'm trying to get familiar with cabin-mesh and noticed that 3 links in Readme are incorrect,
> 
> 1. models - To setup an Casbin model for a specific namespace, executes following request on /set/model endpoint. See all supported [models](https://casbin.org/docs/en/supported-models).
> 2. Policies - Let's add policies for the test namespace. See more of [Policies](https://github.com/casbin/casbin-mesh/blob/main)
> 3. docs - All documents were located in [docs](https://github.com/casbin/casbin-mesh/blob/main/docs) directory.
> 
> I suppose `models` link must point to https://casbin.org/docs/supported-models, is this correct? Could you also please tell where do `Policies` and `docs` are supposed to redirect, I would like to send a PR

I think the `Policies` should also redirect to the https://casbin.org/docs/supported-models, and the `docs` should redirect to the https://mesh.casbin.org/docs/guide/getting-started

**Comment by hsluoyz** [comment]
@harshalmittal4 plz make a PR

**Comment by harshalmittal4** [comment]
Thanks @hsluoyz , @WenyXu, done
